### ISSUE TITLE
invalid controller (login/index)

### ISSUE THREAD

**Issue by alexvinidiktov** [robertop23/web2py_vuejs_vuetify#2]
If I click on the login link when I'm on the home page, the login route is loaded but if I manually enter the address of the login route (http://localhost:8000/web2py_vuejs_vuetify/login) I get the 'invalid controller (login/index) error message.

**Comment by robertop23** [comment]
This is a SPA application, the idea is not use the URL to access Web2py controllers, all must be handled from Vue router.

This is not a big issue, but maybe we can show an "Unauthorized" or something like that instead of show the Invalid controller error

**Comment by robertop23** [comment]
Closed
