### ISSUE TITLE
Do not know how to start.

### ISSUE THREAD

**Issue by luciano-ondir** [robertop23/web2py_vuejs_vuetify#6]
I do not know how to start.
The default/index appears blank.
Other functions appear forbidden (error 403).

If we look at default/index.html, it includes some scripts that are not present at static folder:
  {%if request.is_local:%}
    {%
    response.files.insert(1,URL('static','public/js/app.js'))
    %}
  {% else: %}
    {%
    response.files.insert(1,URL('static','js/manifest.js'))
    response.files.insert(2,URL('static','js/vendor.js'))
    response.files.insert(3,URL('static','js/app.js'))
    %}

What am I missing?

**Comment by alexvinidiktov** [comment]
Did you do "npm install", "npm run watch"?

**Comment by luciano-ondir** [comment]
Yes,
However, as I use Windows, it did work exactly like that.
First, from prompt of command line (as Administrator) I went to folder
web2py_vuejs_vuetify and entered:
             *npm install -g --production windows-build-tools*
After that, I entered "npm install" and "npm run watch".
Anyway, I did not find how to access the pages and how to integrate with
web2py.
Best regards,
Ondir

Em qua, 6 de mar de 2019 às 22:33, Alexei Vinidiktov <
notifications@github.com> escreveu:

**Comment by robertop23** [comment]
The pages are already integrated with Web2py, but with Vue all the frontend
that you need edit is inside resources, not inside Web2py views folder.

Follow the instructions here (I'm not sure if the instructions works on
Windows, I tested only Linux/Mac):
https://github.com/robertop23/web2py_vuejs_vuetify

And go to 127.0.0.1:8000/web2py_vuejs_vuetify

Can we see your "npm run watch" log/result?

Note: You need know the IP and port where is running your Web2py server

**Comment by luciano-ondir** [comment]
Roberto,
Thank you for your attention.
My IP and port are standard (as you can see at the print screen below).
The screen is all blank.

[image: image.png]

the "npm run watch" result is shown at the following figure:
[image: image.png]
I did not understand yet if you are using node as server or if web2py is
the server.
Best regards,
Luciano


Em qui, 7 de mar de 2019 às 11:22, Roberto Perdomo Macedo <
notifications@github.com> escreveu:

**Comment by robertop23** [comment]
We can't see your images, please use something like pastebin to send us your logs

**Comment by robertop23** [comment]
Web2py is the backend and Vue is the frontend. You must understand how it works both first, and then you will know how to join the things here, this is not an web2py_vuejs_vuetify issue

**Comment by luciano-ondir** [comment]
Roberto,

Remembering, the browser screen stays blank when I call "127.0.0.1:8000/web2py_vuejs_vuetify".
The log is the following:

>C:\web2py\applications\web2py_vuejs_vuetify>npm run watch
> @ watch C:\web2py\applications\web2py_vuejs_vuetify
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
>
> 10% building modules 1/1 modules 0 active
>Webpack is watching the files…
>                                                                               95% emitting

My doubt is: 
1) calling "127.0.0.1:8000/web2py_vuejs_vuetify" will make the web2py server return the "default/index.html" page of "web2py_vuejs_vuetify", right?
2) the "index.html" file makes reference to app.js, vendor.js, manifest.js, however, none of them is at "static/js". For me, this explains why the screen is blank. But this is expected?
3) Is there an intermediary server? Should I open other file (at resources folder, for instance)? Should I copy something from resources?
4) How to use a component?

**Comment by robertop23** [comment]
As we can see the npm run watch command has not ended, it must be at
100% and you must see something like this:

 DONE  Compiled successfully in 24862ms

                        Asset         Size Chunks
 Chunk Names
/static/public/js/app.js  10.6 MB       0  [emitted]  [big]
/static/public/js/app
static/public/css/app.css   961 kB       0  [emitted]  [big]
/static/public/js/app

1) Yes and this is calling the vue files:
    response.files.insert(1,URL('static','public/js/app.js'))
    response.files.insert(1,URL('static','public/js/manifest.js'))
    response.files.insert(2,URL('static','public/js/vendor.js'))
    response.files.insert(3,URL('static','public/js/app.js'))
2) This happen because the "npm run watch" has not generated the vue
files for some reason
3) You only need web2py running and have the vue files compiled (npm run watch)
4) What component?

**Comment by eliezerp3** [comment]
@robertop23 ,

I have opened up a new issue, that has to do with this one, labeled "npm run watch freezes at 10%". On Windows, the instructions given do not work. Running "npm run watch" will freeze at 10% with "95% emiting" as shown in my issue. It seems that this is what @luciano-ondir is experiencing also. Love what you have made here and any help would be extremely helpful. Thank You!
#8
